/** Elenco di lingue proponibili nella sezione "Lingue" del profilo, in ordine alfabetico. */
export const LANGUAGES: readonly string[] = [
  'Albanese',
  'Arabo',
  'Armeno',
  'Bengalese',
  'Bulgaro',
  'Catalano',
  'Ceco',
  'Cinese (Mandarino)',
  'Coreano',
  'Croato',
  'Danese',
  'Ebraico',
  'Estone',
  'Filippino (Tagalog)',
  'Finlandese',
  'Francese',
  'Georgiano',
  'Giapponese',
  'Greco',
  'Hindi',
  'Indonesiano',
  'Inglese',
  'Islandese',
  'Italiano',
  'Lettone',
  'Lituano',
  'Macedone',
  'Malese',
  'Norvegese',
  'Olandese',
  'Persiano (Farsi)',
  'Polacco',
  'Portoghese',
  'Rumeno',
  'Russo',
  'Serbo',
  'Slovacco',
  'Sloveno',
  'Spagnolo',
  'Svedese',
  'Tedesco',
  'Thailandese',
  'Turco',
  'Ucraino',
  'Ungherese',
  'Urdu',
  'Vietnamita',
];
