-- =====================================================================
-- V10 - Pagina pubblica aziendale: follow delle aziende, persone
-- autorizzate a gestirla oltre al proprietario, post pubblicati come
-- pagina aziendale e offerte di lavoro.
-- =====================================================================

-- Follow di un'azienda da parte di un utente (stile pagina LinkedIn). Tabella separata da
-- "follows" perché quest'ultima è vincolata a coppie utente-utente (CHECK anti-auto-follow).
CREATE TABLE azienda_follows (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id     NUMBER(19) NOT NULL,
    azienda_id      NUMBER(19) NOT NULL,
    data_creazione  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_azienda_follows UNIQUE (follower_id, azienda_id),
    CONSTRAINT fk_azienda_follows_follower FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_azienda_follows_azienda FOREIGN KEY (azienda_id) REFERENCES aziende (id) ON DELETE CASCADE
);
CREATE INDEX ix_azienda_follows_azienda ON azienda_follows (azienda_id, data_creazione DESC);
CREATE INDEX ix_azienda_follows_follower ON azienda_follows (follower_id, data_creazione DESC);

-- Persone autorizzate a gestire la pagina aziendale (pubblicare post, inserire offerte di lavoro)
-- oltre al proprietario, che resta sempre autorizzato implicitamente senza una riga qui.
CREATE TABLE azienda_autorizzazioni (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id      NUMBER(19) NOT NULL,
    user_id         NUMBER(19) NOT NULL,
    data_creazione  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_azienda_autorizzazioni UNIQUE (azienda_id, user_id),
    CONSTRAINT fk_azienda_autorizzazioni_azienda FOREIGN KEY (azienda_id) REFERENCES aziende (id) ON DELETE CASCADE,
    CONSTRAINT fk_azienda_autorizzazioni_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_azienda_autorizzazioni_azienda ON azienda_autorizzazioni (azienda_id);

-- Collegamento opzionale tra un post e la pagina aziendale per cui è stato pubblicato
-- (in aggiunta ai post personali già esistenti, dove questa colonna resta NULL).
ALTER TABLE posts ADD azienda_id NUMBER(19);
ALTER TABLE posts ADD CONSTRAINT fk_posts_azienda FOREIGN KEY (azienda_id) REFERENCES aziende (id) ON DELETE CASCADE;
CREATE INDEX ix_posts_azienda ON posts (azienda_id, data_creazione DESC);

-- Offerte di lavoro pubblicate da un'azienda. Non esiste una colonna "attiva": un'offerta
-- che non è più disponibile viene eliminata (vedi OffertaLavoroService), così "offerte attive"
-- significa semplicemente "righe presenti per questa azienda". Il limite di 3 è applicativo.
CREATE TABLE offerte_lavoro (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id      NUMBER(19) NOT NULL,
    autore_id       NUMBER(19) NOT NULL,
    titolo          VARCHAR2(200 CHAR) NOT NULL,
    descrizione     VARCHAR2(2000 CHAR),
    data_creazione  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_offerte_lavoro_azienda FOREIGN KEY (azienda_id) REFERENCES aziende (id) ON DELETE CASCADE,
    CONSTRAINT fk_offerte_lavoro_autore FOREIGN KEY (autore_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_offerte_lavoro_azienda ON offerte_lavoro (azienda_id, data_creazione DESC);
