-- =====================================================================
-- V11 - Ruoli e capability per la Dashboard di gestione della pagina
-- aziendale. Sostituisce concettualmente "azienda_autorizzazioni" (V10),
-- che resta in tabella (non distruttivo) ma non viene più consultata da
-- nessun nuovo controllo di autorizzazione una volta completata questa fase.
--
-- Il proprietario dell'azienda non ha mai bisogno di una riga qui: resta
-- sempre Admin implicito e non revocabile (vedi AziendaPermissionService).
-- =====================================================================

-- Ruoli assegnabili ai dipendenti (catalogo fisso, editabile solo via dati).
CREATE TABLE azienda_ruoli (
    id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice VARCHAR2(30 CHAR) NOT NULL,
    nome   VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT uq_azienda_ruoli_codice UNIQUE (codice)
);

INSERT INTO azienda_ruoli (codice, nome) VALUES ('ADMIN', 'Admin');
INSERT INTO azienda_ruoli (codice, nome) VALUES ('HR', 'Risorse Umane');
INSERT INTO azienda_ruoli (codice, nome) VALUES ('SOCIAL_MEDIA_MANAGER', 'Social Media Manager');

-- Capability comprese in ciascun ruolo (matrice di default dal brief prodotto).
CREATE TABLE azienda_ruolo_capabilities (
    ruolo_id   NUMBER(19) NOT NULL,
    capability VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT pk_azienda_ruolo_capabilities PRIMARY KEY (ruolo_id, capability),
    CONSTRAINT fk_azienda_ruolo_capabilities_ruolo FOREIGN KEY (ruolo_id) REFERENCES azienda_ruoli (id) ON DELETE CASCADE
);

INSERT INTO azienda_ruolo_capabilities (ruolo_id, capability)
    SELECT id, 'VIEW_DASHBOARD' FROM azienda_ruoli WHERE codice = 'ADMIN'
    UNION ALL SELECT id, 'MANAGE_POSTS' FROM azienda_ruoli WHERE codice = 'ADMIN'
    UNION ALL SELECT id, 'MANAGE_JOBS' FROM azienda_ruoli WHERE codice = 'ADMIN'
    UNION ALL SELECT id, 'MANAGE_OVERVIEW' FROM azienda_ruoli WHERE codice = 'ADMIN'
    UNION ALL SELECT id, 'MANAGE_PERMISSIONS' FROM azienda_ruoli WHERE codice = 'ADMIN';

INSERT INTO azienda_ruolo_capabilities (ruolo_id, capability)
    SELECT id, 'VIEW_DASHBOARD' FROM azienda_ruoli WHERE codice = 'HR'
    UNION ALL SELECT id, 'MANAGE_JOBS' FROM azienda_ruoli WHERE codice = 'HR';

INSERT INTO azienda_ruolo_capabilities (ruolo_id, capability)
    SELECT id, 'VIEW_DASHBOARD' FROM azienda_ruoli WHERE codice = 'SOCIAL_MEDIA_MANAGER'
    UNION ALL SELECT id, 'MANAGE_POSTS' FROM azienda_ruoli WHERE codice = 'SOCIAL_MEDIA_MANAGER';

-- Assegnazioni di un ruolo a un dipendente. Una riga con data_revoca NULL è "attiva"; una riga
-- revocata non viene mai cancellata (storico per l'audit log), solo chiusa.
CREATE TABLE azienda_user_ruoli (
    id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id        NUMBER(19) NOT NULL,
    user_id           NUMBER(19) NOT NULL,
    ruolo_id          NUMBER(19) NOT NULL,
    assegnato_da_id   NUMBER(19) NOT NULL,
    data_assegnazione TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revocato_da_id    NUMBER(19),
    data_revoca       TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_azienda_user_ruoli_azienda FOREIGN KEY (azienda_id) REFERENCES aziende (id) ON DELETE CASCADE,
    CONSTRAINT fk_azienda_user_ruoli_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_azienda_user_ruoli_ruolo FOREIGN KEY (ruolo_id) REFERENCES azienda_ruoli (id),
    CONSTRAINT fk_azienda_user_ruoli_assegnato_da FOREIGN KEY (assegnato_da_id) REFERENCES users (id),
    CONSTRAINT fk_azienda_user_ruoli_revocato_da FOREIGN KEY (revocato_da_id) REFERENCES users (id)
);

-- Oracle non ha indici parziali: un indice funzionale collassa tutte le righe revocate su
-- valori distinti (il proprio id), lasciando un solo valore 0 per la riga "attiva" di ciascuna
-- tripla (azienda, utente, ruolo) - così non possono coesistere due assegnazioni attive uguali.
CREATE UNIQUE INDEX uq_azienda_user_ruoli_attivo ON azienda_user_ruoli (
    azienda_id, user_id, ruolo_id, (CASE WHEN data_revoca IS NULL THEN 0 ELSE id END)
);
CREATE INDEX ix_azienda_user_ruoli_azienda ON azienda_user_ruoli (azienda_id, data_revoca);
CREATE INDEX ix_azienda_user_ruoli_user ON azienda_user_ruoli (user_id, data_revoca);

-- Log di audit delle modifiche ai permessi (chi/cosa/quando), consultabile dagli Admin.
CREATE TABLE azienda_permessi_audit_log (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id     NUMBER(19) NOT NULL,
    attore_id      NUMBER(19) NOT NULL,
    target_user_id NUMBER(19) NOT NULL,
    ruolo_codice   VARCHAR2(30 CHAR) NOT NULL,
    azione         VARCHAR2(30 CHAR) NOT NULL,
    dettaglio      VARCHAR2(500 CHAR),
    data_evento    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_azienda_permessi_audit_azione CHECK (azione IN ('ASSEGNATO', 'REVOCATO', 'REVOCATO_FINE_RAPPORTO')),
    CONSTRAINT fk_azienda_permessi_audit_azienda FOREIGN KEY (azienda_id) REFERENCES aziende (id) ON DELETE CASCADE,
    CONSTRAINT fk_azienda_permessi_audit_attore FOREIGN KEY (attore_id) REFERENCES users (id),
    CONSTRAINT fk_azienda_permessi_audit_target FOREIGN KEY (target_user_id) REFERENCES users (id)
);
CREATE INDEX ix_azienda_permessi_audit_azienda ON azienda_permessi_audit_log (azienda_id, data_evento DESC);
