-- =====================================================================
-- V15 - Aggregato giornaliero delle metriche della pagina aziendale
-- (Home della Dashboard: visualizzatori unici, follower, like, ricerche).
--
-- Unica tabella durevole: gli eventi grezzi (viste, follow/unfollow,
-- like/unlike, ricerche) NON vengono conservati riga per riga, solo
-- aggregati qui giorno per giorno, così il grafico non esegue mai query
-- pesanti sullo storico. La deduplica a breve termine (visualizzatori
-- unici, apparizioni nei risultati di ricerca) avviene in Redis, non qui.
--
-- FOLLOWER_DELTA e LIKE_DELTA sono variazioni (+1/-1), non totali: il
-- valore nel tempo si ottiene sommando cumulativamente, così un unfollow
-- o un unlike si riflette naturalmente senza dover conservare i singoli
-- timestamp di follow/unfollow.
-- =====================================================================

CREATE TABLE azienda_metric_daily (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azienda_id NUMBER(19) NOT NULL,
    giorno     DATE NOT NULL,
    metrica    VARCHAR2(30 CHAR) NOT NULL,
    valore     NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT ck_azienda_metric_daily_metrica CHECK (metrica IN
        ('VISUALIZZATORI_UNICI', 'FOLLOWER_DELTA', 'LIKE_DELTA', 'RICERCHE')),
    CONSTRAINT uq_azienda_metric_daily UNIQUE (azienda_id, giorno, metrica),
    CONSTRAINT fk_azienda_metric_daily_azienda FOREIGN KEY (azienda_id) REFERENCES aziende (id) ON DELETE CASCADE
);
CREATE INDEX ix_azienda_metric_daily ON azienda_metric_daily (azienda_id, metrica, giorno);
