-- =====================================================================
-- V14 - Scadenza delle offerte di lavoro (7 giorni dalla pubblicazione,
-- vedi DashboardProperties.jobDurationDays) e flusso minimo di
-- candidatura. Lo stato "stato" è una cache aggiornata dallo scheduler
-- di pulizia: ogni lettura ricalcola comunque lo stato effettivo
-- confrontando data_scadenza con l'istante corrente (vedi
-- OffertaLavoroMapper), quindi la cache non è mai l'unica fonte di verità.
-- =====================================================================

ALTER TABLE offerte_lavoro ADD data_scadenza TIMESTAMP(6) WITH TIME ZONE;
UPDATE offerte_lavoro SET data_scadenza = data_creazione + NUMTODSINTERVAL(7, 'DAY') WHERE data_scadenza IS NULL;
ALTER TABLE offerte_lavoro MODIFY data_scadenza NOT NULL;

ALTER TABLE offerte_lavoro ADD stato VARCHAR2(20 CHAR) DEFAULT 'ATTIVA' NOT NULL;
ALTER TABLE offerte_lavoro ADD CONSTRAINT ck_offerte_lavoro_stato CHECK (stato IN ('ATTIVA', 'SCADUTA'));

CREATE INDEX ix_offerte_lavoro_scadenza ON offerte_lavoro (azienda_id, stato, data_scadenza);

-- Candidature: flusso minimo (nessuna versione precedente esisteva). Le candidature seguono la
-- stessa retention della loro offerta tramite ON DELETE CASCADE.
CREATE TABLE candidature_lavoro (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offerta_id     NUMBER(19) NOT NULL,
    candidato_id   NUMBER(19) NOT NULL,
    messaggio      VARCHAR2(2000 CHAR),
    stato          VARCHAR2(20 CHAR) DEFAULT 'INVIATA' NOT NULL,
    data_creazione TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_candidature_stato CHECK (stato IN ('INVIATA', 'VISUALIZZATA', 'ACCETTATA', 'RIFIUTATA')),
    CONSTRAINT uq_candidature_lavoro UNIQUE (offerta_id, candidato_id),
    CONSTRAINT fk_candidature_offerta FOREIGN KEY (offerta_id) REFERENCES offerte_lavoro (id) ON DELETE CASCADE,
    CONSTRAINT fk_candidature_candidato FOREIGN KEY (candidato_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_candidature_offerta ON candidature_lavoro (offerta_id, data_creazione DESC);
