-- =====================================================================
-- V16 - Lingue conosciute dal profilo (livello separato per scritto e parlato)
-- =====================================================================

CREATE TABLE languages (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id       NUMBER(19) NOT NULL,
    lingua           VARCHAR2(60 CHAR) NOT NULL,
    livello_scritto  VARCHAR2(30 CHAR) NOT NULL,
    livello_parlato  VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT fk_languages_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT ck_languages_livello_scritto CHECK (livello_scritto IN ('BASE', 'INTERMEDIO', 'CONOSCENZA_PROFESSIONALE', 'MADRELINGUA')),
    CONSTRAINT ck_languages_livello_parlato CHECK (livello_parlato IN ('BASE', 'INTERMEDIO', 'CONOSCENZA_PROFESSIONALE', 'MADRELINGUA'))
);
CREATE INDEX ix_languages_profile ON languages (profile_id);
