-- =====================================================================
-- V1 - Schema di autenticazione (utenti, ruoli, associazione utente-ruolo)
-- Database: Oracle 23 Free. Hibernate è in modalità "validate": lo schema
-- è di proprietà di Flyway e deve corrispondere alle entità User e Role.
-- =====================================================================

-- Ruoli applicativi (RBAC)
CREATE TABLE roles (
    id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT uq_roles_name UNIQUE (name)
);

-- Utenti registrati (password sempre cifrata con BCrypt)
CREATE TABLE users (
    id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR2(150 CHAR) NOT NULL,
    email    VARCHAR2(255 CHAR) NOT NULL,
    password VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- Tabella di join Many-to-Many tra utenti e ruoli
CREATE TABLE user_roles (
    user_id NUMBER(19) NOT NULL,
    role_id NUMBER(19) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

-- Ruoli di base: devono esistere prima di qualsiasi registrazione
INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
