-- =====================================================================
-- V3 - Profilo professionale (profilo, esperienze, istruzione)
-- Ogni utente ha esattamente un profilo (relazione 1-1 con users),
-- creato alla registrazione. Esperienze e istruzione appartengono al
-- profilo e vengono cancellate insieme a lui.
-- =====================================================================

CREATE TABLE profiles (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             NUMBER(19) NOT NULL,
    profile_picture_url VARCHAR2(1000 CHAR),
    banner_url          VARCHAR2(1000 CHAR),
    sommario            VARCHAR2(500 CHAR),
    CONSTRAINT uq_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Esperienze lavorative (data_end NULL = posizione attuale)
CREATE TABLE experiences (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  NUMBER(19) NOT NULL,
    azienda     VARCHAR2(200 CHAR) NOT NULL,
    ruolo       VARCHAR2(150 CHAR) NOT NULL,
    data_start  DATE NOT NULL,
    data_end    DATE,
    descrizione VARCHAR2(2000 CHAR),
    CONSTRAINT fk_experiences_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_experiences_profile ON experiences (profile_id);

-- Percorsi di studio (data_end NULL = in corso)
CREATE TABLE educations (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id    NUMBER(19) NOT NULL,
    istituto      VARCHAR2(200 CHAR) NOT NULL,
    titolo_studio VARCHAR2(200 CHAR) NOT NULL,
    data_start    DATE NOT NULL,
    data_end      DATE,
    CONSTRAINT fk_educations_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_educations_profile ON educations (profile_id);

-- Profilo vuoto per gli utenti registrati prima di questa migration
INSERT INTO profiles (user_id) SELECT id FROM users;
