-- =====================================================================
-- V4 - Post della community e like
-- Un post ha un testo e/o una foto (almeno uno dei due, controllato
-- anche dall'API). Un utente può mettere al massimo un like per post.
-- =====================================================================

CREATE TABLE posts (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autore_id       NUMBER(19) NOT NULL,
    contenuto       VARCHAR2(3000 CHAR),
    media_url       VARCHAR2(1000 CHAR),
    data_creazione  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_posts_autore FOREIGN KEY (autore_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_posts_non_vuoto CHECK (contenuto IS NOT NULL OR media_url IS NOT NULL)
);
-- Feed globale (ordinato per data) e post di un singolo autore
CREATE INDEX ix_posts_data_creazione ON posts (data_creazione DESC, id DESC);
CREATE INDEX ix_posts_autore ON posts (autore_id, data_creazione DESC);

CREATE TABLE post_likes (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         NUMBER(19) NOT NULL,
    user_id         NUMBER(19) NOT NULL,
    data_creazione  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_post_likes UNIQUE (post_id, user_id),
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_post_likes_user ON post_likes (user_id);
