-- =====================================================================
-- V5 - Relazione di "follow" tra utenti (stile LinkedIn)
-- Un utente può seguire un altro utente al massimo una volta e non può
-- seguire se stesso (vincolo controllato anche a livello applicativo).
-- =====================================================================

CREATE TABLE follows (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id     NUMBER(19) NOT NULL,
    followed_id     NUMBER(19) NOT NULL,
    data_creazione  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_follows UNIQUE (follower_id, followed_id),
    CONSTRAINT fk_follows_follower FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_follows_followed FOREIGN KEY (followed_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_follows_no_self CHECK (follower_id <> followed_id)
);
-- Elenco "chi segue X" (followers) ed elenco "chi segue X" (following) sono entrambi frequenti
CREATE INDEX ix_follows_followed ON follows (followed_id, data_creazione DESC);
CREATE INDEX ix_follows_follower ON follows (follower_id, data_creazione DESC);
