-- =====================================================================
-- V6 - Recensioni tra colleghi
-- Un utente può lasciare una sola recensione a un altro utente: se la
-- rifà, aggiorna quella esistente invece di crearne una seconda.
-- Il requisito di sicurezza "stesso locale, periodo sovrapposto" è
-- applicativo, non a database: vedi ReviewService#hasOverlappingExperience.
-- =====================================================================

CREATE TABLE reviews (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autore_id           NUMBER(19) NOT NULL,
    destinatario_id     NUMBER(19) NOT NULL,
    valutazione         NUMBER(1) NOT NULL,
    testo               VARCHAR2(2000 CHAR) NOT NULL,
    data_creazione      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    data_aggiornamento  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_reviews UNIQUE (autore_id, destinatario_id),
    CONSTRAINT fk_reviews_autore FOREIGN KEY (autore_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_destinatario FOREIGN KEY (destinatario_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_reviews_no_self CHECK (autore_id <> destinatario_id),
    CONSTRAINT ck_reviews_valutazione CHECK (valutazione BETWEEN 1 AND 5)
);
-- Elenco recensioni ricevute da un utente (profilo), dalla più recente
CREATE INDEX ix_reviews_destinatario ON reviews (destinatario_id, data_creazione DESC);
CREATE INDEX ix_reviews_autore ON reviews (autore_id);
