-- =====================================================================
-- V7 - Aziende (ristoranti, locali, attività di ristorazione)
-- Ogni utente autenticato può creare più aziende; solo il proprietario
-- può modificarla o eliminarla (controllo applicativo in AziendaService).
-- =====================================================================

CREATE TABLE aziende (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proprietario_id NUMBER(19) NOT NULL,
    nome            VARCHAR2(200 CHAR) NOT NULL,
    tipo            VARCHAR2(50 CHAR) NOT NULL,
    descrizione     VARCHAR2(2000 CHAR),
    indirizzo       VARCHAR2(300 CHAR),
    citta           VARCHAR2(100 CHAR),
    telefono        VARCHAR2(30 CHAR),
    email           VARCHAR2(255 CHAR),
    sito_web_url    VARCHAR2(1000 CHAR),
    data_creazione  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_aziende_proprietario FOREIGN KEY (proprietario_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_aziende_tipo CHECK (tipo IN ('RISTORANTE', 'PIZZERIA', 'BAR', 'HOTEL', 'CATERING', 'ALTRO'))
);
-- Elenco aziende di un utente, ed elenco generale, entrambi dal più recente
CREATE INDEX ix_aziende_proprietario ON aziende (proprietario_id, data_creazione DESC);
CREATE INDEX ix_aziende_data_creazione ON aziende (data_creazione DESC, id DESC);
